name = "ScientificComputingBenchmarks"
uuid = "64d95ac0-a14d-11e8-2ace-250427308d42"
authors = ["Jonathan Bieler <jonathan.bieler@alumni.epfl.ch>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
